version: '3'
services:
  backend:
    build: ./Online Banking App Spring Boot
    ports:
      - "8070:8070"
    networks:
      - app-network
    

  frontend:
    build: ./demo-bank-redux
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

